- countries: [austria]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-austria.pkl
- countries: [belgium]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-belgium.pkl
- countries: [bulgaria]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-bulgaria.pkl
- countries: [croatia]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-croatia.pkl
- countries: [cyprus]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-cyprus.pkl
- countries: [czechia]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-czechia.pkl
- countries: [denmark]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-denmark.pkl
- countries: [estonia]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-estonia.pkl
- countries: [finland]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-finland.pkl
- countries: [france]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-france.pkl
- countries: [germany]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-germany.pkl
- countries: [greece]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-greece.pkl
- countries: [hungary]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-hungary.pkl
- countries: [ireland]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-ireland.pkl
- countries: [italy]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-italy.pkl
- countries: [latvia]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-latvia.pkl
- countries: [lithuania]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-lithuania.pkl
- countries: [luxembourg]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-luxembourg.pkl
- countries: [malta]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-malta.pkl
- countries: [netherlands]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-netherlands.pkl
- countries: [poland]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-poland.pkl
- countries: [portugal]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-portugal.pkl
- countries: [romania]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-romania.pkl
- countries: [slovakia]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-slovakia.pkl
- countries: [slovenia]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-slovenia.pkl
- countries: [spain]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-spain.pkl
- countries: [sweden]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-sweden.pkl
- countries: [switzerland]
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
  file_path: /p/projects/eubucco/data/3-ml-inputs-v0_1/df-switzerland.pkl
