jobs:
   - name: create-training-dataset
     script: /p/projects/eubucco/git-eubucco/database/feature-engineering/fts_concat.py
     param_files:
       - /p/projects/eubucco/git-eubucco/database/feature-engineering/params-new.yml
     log_dir: /p/projects/eubucco/logs/v0_1-db/create-training-dataset
     resources:
       cpus: 8
       mem: 62000
       time: "12:00:00"
     #special_cases:
     #  - name: small-countries
     #    files:
     #      path: "{{data_dir}}/{{country}}"
     #      size_max: 10000000000
     #    resources:
     #      cpus: 4
     #      mem: 30000
     #  - name: large-countries
     #    files:
     #      path: "{{data_dir}}/{{country}}"
     #      size_min: 50000000000
     #    resources:
     #      cpus: 8
     #      mem: 126000

properties:
  conda_env: "/home/nikolami/.conda/envs/ox112"
  account: eubucco
  log_level: INFO
  exp_backoff_factor: 4
  max_retries: 3
  poll_interval: 30
  slack:
    channel: "#test-slurm-bot"
    token: <to-be-added>

