jobs:
  - name: create-release
    script: /p/projects/eubucco/git-eubucco/database/preprocessing/5-release/run_create_submission.py
    param_files:
      - /p/projects/eubucco/git-eubucco/database/preprocessing/5-release/params_msft.yml
    log_dir: /p/projects/eubucco/logs-tmp/v1/release

    resources:
      cpus: 16
      time: "24:00:00"

properties:
  conda_env: "/home/nikolami/.conda/envs/ox112"
  account: eubucco
  log_level: INFO
  exp_backoff_factor: 4
  max_retries: 3
  poll_interval: 30

