jobs:
  - name: db-set-up-microsoft
    script: /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/db-set-up.py
    param_files:
      - /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/params-microsoft-test.csv
    log_dir: /p/projects/eubucco/logs/v0_1-db/db-set-up-microsoft
    resources:
      cpus: 4
      time: "01:00:00"
    special_cases:
      - name: small-files
        files:
          path: "/p/projects/eubucco/data/1-intermediary-outputs-microsoft/{{country}}/{{dataset_name}}-3035_geoms.csv"
          size_min: 10000000
          size_max: 20000000
        resources:
          time: "02:00:00"


properties:
  conda_env: "/home/nikolami/.conda/envs/ox112"
  account: eubucco
  log_level: INFO
  exp_backoff_factor: 4
  max_retries: 3
  poll_interval: 30
  slack:
    channel: "#test-slurm-bot"
    token: xoxb-2181800768432-3591454355235-XxTRN4mQidN8x81UmlFg860b

