jobs:
  - name: 2-db-set-up
    script: /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/db-set-up.py
    param_files:
      - /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/params-gov.csv
      - /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/params-osm.csv
      - /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/params-msft.csv
    log_dir: /p/projects/eubucco/logs/v1_0-db/2-db-set-up
    resources:
      cpus: 1
      time: "03:00:00"

  - name: 2-db-set-up-merge
    script: /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/db-set-up.py
    param_files:
      - /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/params-merge.csv
    log_dir: /p/projects/eubucco/logs/v1_0-db/2-db-set-up-merge
    resources:
      cpus: 1
      time: "03:00:00"

  - name: 3-attrib-cleaning
    script: /p/projects/eubucco/git-eubucco/database/preprocessing/3-attrib-cleaning/attrib_cleaning.py
    param_files: [/p/projects/eubucco/git-eubucco/database/preprocessing/3-attrib-cleaning/params.yml]
    log_dir: /p/projects/eubucco/logs/v1_0-db/attrib-cleaning
    resources:
      cpus: 16
      time: "7-00:00:00"

  - name: 4-conflation
    script: /p/projects/eubucco/eubucco-conflation/slurm-pipeline/conflate.py
    param_generator_file: /p/projects/eubucco/eubucco-conflation/slurm-pipeline/params-conflation.yml
    log_dir: /p/projects/eubucco/logs/v1_0-db/conflation
    resources:
      cpus: 16
      mem: 100000
      time: "7-00:00:00"
    special_cases:
      - name: large-regions
        files:
          path: "/p/projects/eubucco/data/3-attrib-cleaning-v1-osm/{{region_id}}.parquet"
          size_min: 100000000
        resources:
          mem: 100000

  - name: 5-download-streets
    script: /p/projects/eubucco/eubucco-features/slurm/download_streets.py
    param_files:
      - /p/projects/eubucco/eubucco-features/slurm/params-download-streets.yml
    log_dir: /p/projects/eubucco/logs/v1_0-db/download-streets
    resources:
      cpus: 1
      partition: io
      mem: 8000
    properties:
      exp_backoff_factor: 2
      max_retries: 1

  - name: 5-download-pois
    script: /p/projects/eubucco/eubucco-features/slurm/download_pois.py
    param_files:
      - /p/projects/eubucco/eubucco-features/slurm/params-download-pois.yml
    log_dir: /p/projects/eubucco/logs/v1_0-db/download-pois
    resources:
      cpus: 1
      partition: io
      mem: 8000
    properties:
      exp_backoff_factor: 2
      max_retries: 1

  - name: 5-feature-engineering
    script: /p/projects/eubucco/eubucco-features/slurm/ft-eng.py
    param_generator_file: /p/projects/eubucco/eubucco-features/slurm/params-ft-eng.yml
    log_dir: /p/projects/eubucco/logs/v1_0-db/feature-engineering
    resources:
      cpus: 8
      mem: 100000
      time: "7-00:00:00"
    special_cases:
      - name: large-regions
        files:
          path: "{{bldgs_dir}}/**/{{region_id}}.parquet"
          size_min: 100000000
        resources:
          mem: 100000

properties:
  conda_env: eubucco-features
  account: eubucco
  log_level: INFO
  exp_backoff_factor: 4
  max_retries: 3
  poll_interval: 30
  slack:
    channel: "#test-slurm-bot"
    token: <to-be-added>

