jobs:
#  - name: parsing-msft
#    script: /p/projects/eubucco/git-eubucco/database/preprocessing/1-parsing/main-parsing.py
#    param_files:
#      - /p/projects/eubucco/git-eubucco/database/preprocessing/1-parsing/inputs-parsing-microsoft.csv
#    log_dir: /p/projects/eubucco/logs-tmp/v1/parsing-msft
#    resources:
#      cpus: 4
#      time: "01:00:00"

 - name: parsing-osm
   script: /p/projects/eubucco/git-eubucco/database/preprocessing/1-parsing/main-parsing.py
   param_files:
     - /p/projects/eubucco/git-eubucco/database/preprocessing/1-parsing/inputs-parsing-osm-24.csv
   log_dir: /p/projects/eubucco/logs-tmp/v1/parsing-msft
   resources:
     cpus: 8
     time: "02:00:00"

#   - name: db-set-up-msft
#     script: /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/db-set-up.py
#     param_files:
#       - /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/params-microsoft24.csv
#     log_dir: /p/projects/eubucco/logs-tmp/v1/db-set-up-msft
#     resources:
#       cpus: 4
#       time: "01:00:00"


# before running this the folders needs to cleaned from existing data
#   - name: db-set-up-msft_2
#     script: /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/db-set-up.py
#     param_files:
#       - /p/projects/eubucco/git-eubucco/database/preprocessing/2-db-set-up/params-microsoft24_2.csv
#     log_dir: /p/projects/eubucco/logs-tmp/v1/db-set-up-msft
#     resources:
#       cpus: 4
#       time: "12:00:00"


  # - name: run-overview
  #   script: /p/projects/eubucco/git-eubucco/database/preprocessing/5-release/run-overview.py
  #   param_files:
  #     - /p/projects/eubucco/git-eubucco/database/preprocessing/5-release/params_overview_msft24.yml
  #   log_dir: /p/projects/eubucco/logs-tmp/v1/release
  #   resources:
  #     cpus: 1

  # - name: create-ids
  #   script: /p/projects/eubucco/git-eubucco/database/preprocessing/4-attrib-cleaning/run_create_id.py
  #   param_files:
  #     - /p/projects/eubucco/git-eubucco/database/preprocessing/4-attrib-cleaning/params_ids_msft24.yml
  #   log_dir: /p/projects/eubucco/logs-tmp/v1/release
  #   resources:
  #     cpus: 2
  #     time: "01:00:00"


  # - name: create-release
  #   script: /p/projects/eubucco/git-eubucco/database/preprocessing/5-release/run_create_submission.py
  #   param_files:
  #     - /p/projects/eubucco/git-eubucco/database/preprocessing/5-release/params_msft24_release.yml
  #   log_dir: /p/projects/eubucco/logs-tmp/v1/release
  #   resources:
  #     cpus: 16
  #     time: "1:00:00"


  # - name: create-release
  #   script: /p/projects/eubucco/git-eubucco/database/preprocessing/5-release/create_example_cities.py
  #   param_files:
  #     - /p/projects/eubucco/git-eubucco/database/preprocessing/5-release/params_example_cities_msft.yml
  #   log_dir: /p/projects/eubucco/logs-tmp/v1/release
  #   resources:
  #     cpus: 6
  #     time: "1:00:00"

properties:
  conda_env: "/home/nikolami/.conda/envs/ox112"
  account: eubucco
  log_level: INFO
  exp_backoff_factor: 4
  max_retries: 3
  poll_interval: 30

