- country: austria
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: belgium
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: bulgaria
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: croatia
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: cyprus
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: czechia
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: denmark
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: estonia
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: finland
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: france
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: germany
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: greece
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: hungary
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: ireland
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: italy
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: latvia
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: lithuania
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: luxembourg
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: malta
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: netherlands
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: poland
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: portugal
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: romania
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: slovakia
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: slovenia
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: spain
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: sweden
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
- country: switzerland
  path_stats: /p/projects/eubucco/stats/6-streets-v0_1
  data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
